#!/bin/sh
#
# Clear the /tmp directory.
#
# Patched for Home Assistant. The supervisor bind-mounts runtime files into
# the container under /tmp/run when the add-on uses audio (the PulseAudio
# socket, read-only) and always the container-id file (in use / busy). The
# stock upstream script runs with `set -e` and does `rm -rf /tmp/run`, which
# aborts container init as soon as it hits one of those unremovable mounts
# (see the "Read-only file system" / "Resource busy" errors). This version
# performs the same best-effort cleanup but never fails init on a mount it
# cannot remove, and it clears the *contents* of /tmp/run instead of trying
# to unlink the mount points themselves.
#

set -u # Treat unset variables as an error.

# Special case for /tmp/run, which might contain Docker secrets and/or
# Home Assistant bind-mounts (audio socket, cid). Clear its contents on a
# best-effort basis; unremovable mounts are expected and tolerated.
if [ -d /tmp/run ]; then
    if df /tmp/run/secrets >/dev/null 2>/dev/null; then
        find /tmp/run -mindepth 1 -maxdepth 1 ! -name 'secrets' -exec rm -rf {} + 2>/dev/null || true
    else
        find /tmp/run -mindepth 1 -maxdepth 1 -exec rm -rf {} + 2>/dev/null || true
    fi
fi

# Remove everything, except:
#   - /tmp/.cont-env-internal: this file has been generated by the init script.
#   - /tmp/run: this directory has been handled previously.
find /tmp -mindepth 1 -maxdepth 1 ! -name '.cont-env-internal' ! -name 'run' -exec rm -rf {} + 2>/dev/null || true

exit 0

# vim:ft=sh:ts=4:sw=4:et:sts=4
